name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ['main'] # Only run on the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: &matrix
        file: [distributed_block_and_object_storages]
    steps:
      - name: Set up Typst
        uses: typst-community/setup-typst@v4
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile Typst
        run: |
          mkdir -p dist
          typst compile ${{ matrix.file }}/src/main.typ dist/${{ matrix.file }}.pdf
      - name: Set Output for PDF Artifact Name
        id: set_output
        run: echo "pdf_artifact_name=trojak_${{ matrix.file }}.pdf" >> $GITHUB_ENV
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}.pdf
          path: dist/${{ matrix.file }}.pdf
  build-index-page:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Build Index Page
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
      - name: Upload Index Page
        uses: actions/upload-artifact@v4
        with:
          name: readme-index-page
          path: index.html
  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          path: public/
      - name: Download Index Page Artifact
        uses: actions/download-artifact@v4
        with:
          name: readme-index-page
          path: public/
      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
